### ISSUE TITLE
Unit test test_nonlinear.py generates error

### ISSUE THREAD

**Issue by denson** [tensorflow/skflow#106]
I get the following error when I run  test_nonlinear.py

[](https://raw.githubusercontent.com/tensorflow/skflow/master/skflow/tests/test_nonlinear.py)

.E.
======================================================================
ERROR: testRNN (__main__.NonLinearTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Volumes/experiments/GFFS_protein_structure_tensorflow/tutorials/unit_test_original_v2.py", line 79, in testRNN
    classifier.fit(data, labels)
  File "/Users/denson/anaconda2/lib/python2.7/site-packages/skflow/estimators/base.py", line 200, in fit
    self._setup_training()
  File "/Users/denson/anaconda2/lib/python2.7/site-packages/skflow/estimators/base.py", line 139, in _setup_training
    self._inp, self._out)
  File "/Users/denson/anaconda2/lib/python2.7/site-packages/skflow/estimators/rnn.py", line 110, in _model_fn
    self.initial_state)(X, y)
  File "/Users/denson/anaconda2/lib/python2.7/site-packages/skflow/models.py", line 251, in rnn_estimator
    return target_predictor_fn(encoding[-1], y)
  File "/Users/denson/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 124, in _SliceHelper
    raise NotImplementedError("Negative indices are currently unsupported")
NotImplementedError: Negative indices are currently unsupported

----------------------------------------------------------------------

**Comment by ilblackdragon** [comment]
Interface of rnn op changed - instead of returning list of states it returns last state only now. 
I'll fix it later today.

**Comment by ilblackdragon** [comment]
Should be fixed with #119 merge.
