### ISSUE TITLE
TypeError inside skflow

### ISSUE THREAD

**Issue by DiegoGLagash** [tensorflow/skflow#168]
I'm running a sample from a tutorial, and I'm getting this error inside skflow:

Traceback (most recent call last):
  File "titanic.py", line 26, in <module>
    tflr.fit(X_train, y_train)
  File "/Users/diegog/Source/tensorflow/lib/python2.7/site-packages/skflow/estimators/base.py", line 227, in fit
    feed_params_fn=self._data_feeder.get_feed_params)
  File "/Users/diegog/Source/tensorflow/lib/python2.7/site-packages/skflow/trainer.py", line 146, in train
    if summaries:
  File "/Users/diegog/Source/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 475, in __nonzero__
    raise TypeError("Using a `tf.Tensor` as a Python `bool` is not allowed. "
TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use the logical TensorFlow ops to test the value of a tensor.

I've tried with the development branch and the error persist. Any idea?

**Comment by ilblackdragon** [comment]
Hi @DiegoGLagash skflow have moved inside tensorflow.
If you update your tensorflow to 0.8 you can use it via `tf.contrib.learn`. This issue is fixed there.

I'll also update this repo to use skflow from inside tensorflow.
