### ISSUE TITLE
Exception in the Custom model example 

### ISSUE THREAD

**Issue by mhjabreel** [tensorflow/skflow#176]
Hi,

I have tried running the custom model example and i got the following exception

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/base.py", line 160, in fit
    monitors=monitors)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 449, in _train_model
    train_op, loss_op = self._get_train_ops(features, targets)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 673, in _get_train_ops
    _, loss, train_op = self._call_model_fn(features, targets, ModeKeys.TRAIN)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 656, in _call_model_fn
    features, targets, mode=mode)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/base.py", line 369, in _model_fn
    predictions, loss = model_fn(features, targets)
  File "<stdin>", line 3, in my_model
TypeError: dnn() got an unexpected keyword argument 'keep_prob'

Any ideas what might be causing this?

**Comment by ilblackdragon** [comment]
Which example did you run? Please use examples from https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/skflow
Also if something doesn't work, please post in that repo (this repo is inactive at this point).

**Comment by ilblackdragon** [comment]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/skflow/iris_custom_model.py shows how to use new tf.contrib.layers for dnn with dropout.
