### ISSUE TITLE
getting none values not supported error

### ISSUE THREAD

**Issue by vinayakumarr** [tensorflow/skflow#179]
python neural_translation.py

Traceback (most recent call last):
  File "neural_translation.py", line 121, in <module>
    translator.fit(x_iter, y_iter, logdir=PATH)
  File "/Library/Python/2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/base.py", line 227, in fit
    self._setup_training()
  File "/Library/Python/2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/base.py", line 163, in _setup_training
    optimizer=optimizer, clip_gradients=self.clip_gradients)
  File "/Library/Python/2.7/site-packages/tensorflow/contrib/layers/python/layers/optimizers.py", line 141, in optimize_loss
    logging_ops.histogram_summary(variable.name + "/gradients", grad_values)
  File "/Library/Python/2.7/site-packages/tensorflow/python/ops/logging_ops.py", line 113, in histogram_summary
    tag=tag, values=values, name=scope)
  File "/Library/Python/2.7/site-packages/tensorflow/python/ops/gen_logging_ops.py", line 55, in _histogram_summary
    name=name)
  File "/Library/Python/2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 415, in apply_op
    as_ref=input_arg.is_ref).dtype.name
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/ops.py", line 566, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/Library/Python/2.7/site-packages/tensorflow/python/ops/constant_op.py", line 179, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/Library/Python/2.7/site-packages/tensorflow/python/ops/constant_op.py", line 162, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape))
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 325, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.

how to correct this

i am using tensorflow version 0.8 and in linux

**Comment by ilblackdragon** [comment]
This seems like you have trainable variables without gradients. Can you
show your variables (print tf.all_variables) and probably gradients in
optimize_loss? Also you should try updating to 0.9 - there has been a lot
of issues addressed there.

**Comment by terrytangyuan** [comment]
There has been a lot of bug fixes since 0.8. Please try latest version. Please submit an issue to TensorFlow repo in the future instead.

**Comment by shadiakiki1986** [comment]
Possibly answered on StackOverflow [here](https://stackoverflow.com/a/45025025/4126114)
